# Generated by Django 4.2.1 on 2023-09-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
